# Use the official PHP 8.2 image with Apache as the base image
FROM php:8.2-apache

# Set the installation directory for the web application
ENV INSTALL_DIR /var/www/html

# Update the package lists and upgrade installed packages
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
    wget unzip zip zlib1g-dev libfreetype6-dev libpng-dev \
    libzip-dev libc-client-dev libjpeg-dev libkrb5-dev ghostscript\
    wait-for-it libcurl3-dev; \
    apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Configure and install PHP extensions: IMAP, GD, ZIP, BCMath, Opcache, EXIF, MySQLi
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) imap gd zip bcmath opcache exif mysqli curl

RUN a2enmod rewrite

ENV VERSION 3.0.3.9

RUN set -eux; \
	curl -o opencart.zip -fL "https://github.com/opencart/opencart/releases/download/${VERSION}/opencart-${VERSION}.zip"; \
	unzip opencart.zip -d /usr/src/opencart; \
	rm opencart.zip; \
	[ ! -e /usr/src/opencart/upload/.htaccess ]; \
    cp /usr/src/opencart/upload/.htaccess.txt  /usr/src/opencart/upload/.htaccess; \
	\
	chown -R www-data:www-data /usr/src/opencart; \
    mkdir /var/www/opencart-storage; \
    chown www-data:www-data /var/www/opencart-storage

VOLUME /var/www/html

VOLUME /var/www/opencart-storage

COPY --chmod=755 docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

# Set the user and group to run the container as (www-data is the Apache user)
USER www-data:www-data

# Set the working directory to the installation directory
WORKDIR $INSTALL_DIR

# Expose port 80 to allow external connections to the web server
EXPOSE 80

ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["apache2-foreground"]